services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false
        bind:
            $studioWysiwygConfiguration: '%pimcore_studio_ui.wysiwyg_configuration%'
            $studioUrlUrlPath: '%pimcore_studio_ui.url_path%'

    Pimcore\Bundle\StudioUiBundle\Controller\DefaultController:
        public: true
        tags: ['controller.service_arguments']
        arguments:
            $staticResourcesResolver: '@pimcore_studio.static_resources_resolver.default'

    Pimcore\Bundle\StudioUiBundle\Controller\Backend\:
        resource: '../src/Controller/Backend'
        public: true
        tags: [ 'controller.service_arguments' ]

    # Document version comparison service
    Pimcore\Bundle\StudioUiBundle\Document\DocumentVersionComparisonService:
        autowire: true

    pimcore_studio.static_resources_resolver.default:
        class: Pimcore\Bundle\StudioUiBundle\Service\StaticResourcesResolver
        arguments:
            $webpackEntryPointManager: '@pimcore_studio.entry_point_manager.default'

    pimcore_studio.entry_point_manager.default:
        class: Pimcore\Bundle\StudioUiBundle\Webpack\WebpackEntryPointManager
        arguments:
            - !tagged_iterator pimcore_studio_ui.webpack_entry_point_provider

    pimcore_studio.static_resources_resolver.document_editor_iframe:
        class: Pimcore\Bundle\StudioUiBundle\Service\StaticResourcesResolver
        arguments:
            $webpackEntryPointManager: '@pimcore_studio.entry_point_manager.document_editor_iframe'

    pimcore_studio.entry_point_manager.document_editor_iframe:
        class: Pimcore\Bundle\StudioUiBundle\Webpack\WebpackEntryPointManager
        arguments:
            - !tagged_iterator pimcore_studio_ui.webpack_entry_point_provider.document_editor_iframe

    Pimcore\Bundle\StudioUiBundle\Webpack\WebpackEntryPointProvider: 
        tags:
           - { name: 'pimcore_studio_ui.webpack_entry_point_provider' }

    Pimcore\Bundle\StudioUiBundle\Webpack\WebpackEntryPointProviderDocumentEditorIframe:
        tags:
            - { name: 'pimcore_studio_ui.webpack_entry_point_provider.document_editor_iframe' }

    Pimcore\Bundle\StudioUiBundle\EventSubscriber\EditmodeSubscriber:
        tags: ['kernel.event_subscriber']
        arguments:
            $staticResourcesResolver: '@pimcore_studio.static_resources_resolver.document_editor_iframe'
        calls:
            - [ setLogger, [ '@logger' ] ]

    Pimcore\Bundle\StudioUiBundle\Installer:
        public: true
        arguments:
            $bundle: "@=service('kernel').getBundle('PimcoreStudioUiBundle')"

# add more services, or override services that need manual wiring
#    Pimcore\Bundle\StudioUiBundle\ExampleClass:
#        arguments:
#            - "@service_id"
#            - "plain_value"
#            - "%parameter%"