/**
 * This source file is available under the terms of the
 * Pimcore Open Core License (POCL)
 * Full copyright and license information is available in
 * LICENSE.md which is distributed with this source code.
 *
 *  @copyright  Copyright (c) Pimcore GmbH (https://www.pimcore.com)
 *  @license    Pimcore Open Core License (POCL)
 */

/* eslint-disable max-lines */
export const dynamicTypeRegistriesServiceIds = {
  'DynamicTypes/FieldFilterRegistry': 'DynamicTypes/FieldFilterRegistry',
  'DynamicTypes/BatchEditRegistry': 'DynamicTypes/BatchEditRegistry',
  'DynamicTypes/GridCellRegistry': 'DynamicTypes/GridCellRegistry',
  'DynamicTypes/AdvancedGridCellRegistry': 'DynamicTypes/AdvancedGridCellRegistry',
  'DynamicTypes/ListingRegistry': 'DynamicTypes/ListingRegistry',
  'DynamicTypes/MetadataRegistry': 'DynamicTypes/MetadataRegistry',
  'DynamicTypes/CustomReportDefinitionRegistry': 'DynamicTypes/CustomReportDefinitionRegistry',
  'DynamicTypes/ObjectLayoutRegistry': 'DynamicTypes/ObjectLayoutRegistry',
  'DynamicTypes/ObjectDataRegistry': 'DynamicTypes/ObjectDataRegistry',
  'DynamicTypes/DocumentEditableRegistry': 'DynamicTypes/DocumentEditableRegistry',
  'DynamicTypes/EditableDialogLayoutRegistry': 'DynamicTypes/EditableDialogLayoutRegistry',
  'DynamicTypes/AssetRegistry': 'DynamicTypes/AssetRegistry',
  'DynamicTypes/DocumentRegistry': 'DynamicTypes/DocumentRegistry',
  'DynamicTypes/ObjectRegistry': 'DynamicTypes/ObjectRegistry',
  'DynamicTypes/Grid/SourceFieldsRegistry': 'DynamicTypes/Grid/SourceFieldsRegistry',
  'DynamicTypes/Grid/TransformersRegistry': 'DynamicTypes/Grid/TransformersRegistry',
  'DynamicTypes/ThemeRegistry': 'DynamicTypes/ThemeRegistry',
  'DynamicTypes/IconSetRegistry': 'DynamicTypes/IconSetRegistry',
  'DynamicTypes/IconSet/PimcoreDefault': 'DynamicTypes/IconSet/PimcoreDefault',
  'DynamicTypes/IconSet/Twemoji': 'DynamicTypes/IconSet/Twemoji',
  'DynamicTypes/WidgetEditor/WidgetTypeRegistry': 'DynamicTypes/WidgetEditor/WidgetTypeRegistry',
  'DynamicTypes/FieldDefinitionRegistry': 'DynamicTypes/FieldDefinitionRegistry',
  'DynamicTypes/GDPRProviderRegistry': 'DynamicTypes/GDPRProviderRegistry',
  'DynamicTypes/TransformationDynamicTypeRegistry': 'image-thumbnails.transformation-dynamic-type-registry',
  'DynamicTypes/TransformationFieldCollectionRegistry': 'image-thumbnails.transformation-field-collection-registry',
  'DynamicTypes/Transformation/Cover': 'DynamicTypes/Transformation/Cover',
  'DynamicTypes/Transformation/Resize': 'DynamicTypes/Transformation/Resize',
  'DynamicTypes/Transformation/ScaleByWidth': 'DynamicTypes/Transformation/ScaleByWidth',
  'DynamicTypes/Transformation/ScaleByHeight': 'DynamicTypes/Transformation/ScaleByHeight',
  'DynamicTypes/Transformation/Trim': 'DynamicTypes/Transformation/Trim',
  'DynamicTypes/Transformation/Sepia': 'DynamicTypes/Transformation/Sepia',
  'DynamicTypes/Transformation/Grayscale': 'DynamicTypes/Transformation/Grayscale',
  'DynamicTypes/Transformation/Sharpen': 'DynamicTypes/Transformation/Sharpen',
  'DynamicTypes/Transformation/Contain': 'DynamicTypes/Transformation/Contain',
  'DynamicTypes/Transformation/Crop': 'DynamicTypes/Transformation/Crop',
  'DynamicTypes/Transformation/Frame': 'DynamicTypes/Transformation/Frame',
  'DynamicTypes/Transformation/Rotate': 'DynamicTypes/Transformation/Rotate',
  'DynamicTypes/Transformation/Mirror': 'DynamicTypes/Transformation/Mirror',
  'DynamicTypes/Transformation/GaussianBlur': 'DynamicTypes/Transformation/GaussianBlur',
  'DynamicTypes/Transformation/BrightnessSaturation': 'DynamicTypes/Transformation/BrightnessSaturation',
  'DynamicTypes/Transformation/SetBackgroundColor': 'DynamicTypes/Transformation/SetBackgroundColor',
  'DynamicTypes/Transformation/SetBackgroundImage': 'DynamicTypes/Transformation/SetBackgroundImage',
  'DynamicTypes/Transformation/RoundCorners': 'DynamicTypes/Transformation/RoundCorners',
  'DynamicTypes/Transformation/AddOverlay': 'DynamicTypes/Transformation/AddOverlay',
  'DynamicTypes/Transformation/AddOverlayFit': 'DynamicTypes/Transformation/AddOverlayFit',
  'DynamicTypes/Transformation/ApplyMask': 'DynamicTypes/Transformation/ApplyMask',
  'DynamicTypes/Transformation/TiffOriginal': 'DynamicTypes/Transformation/TiffOriginal',
  'DynamicTypes/Transformation/OnePixel': 'DynamicTypes/Transformation/OnePixel',
  'DynamicTypes/VideoTransformationDynamicTypeRegistry': 'video-thumbnails.transformation-dynamic-type-registry',
  'DynamicTypes/VideoTransformationFieldCollectionRegistry': 'video-thumbnails.transformation-field-collection-registry',
  'DynamicTypes/VideoTransformation/Resize': 'DynamicTypes/VideoTransformation/Resize',
  'DynamicTypes/VideoTransformation/ScaleByWidth': 'DynamicTypes/VideoTransformation/ScaleByWidth',
  'DynamicTypes/VideoTransformation/ScaleByHeight': 'DynamicTypes/VideoTransformation/ScaleByHeight',
  'DynamicTypes/VideoTransformation/Cut': 'DynamicTypes/VideoTransformation/Cut',
  'DynamicTypes/VideoTransformation/SetFramerate': 'DynamicTypes/VideoTransformation/SetFramerate',
  'DynamicTypes/VideoTransformation/ColorChannelMixer': 'DynamicTypes/VideoTransformation/ColorChannelMixer',
  'DynamicTypes/VideoTransformation/Mute': 'DynamicTypes/VideoTransformation/Mute'
}

export const serviceIds = {
  // Main nav
  mainNavRegistry: 'MainNavRegistry',

  // Perspective Editor
  perspectivePermissionProviderRegistry: 'PerspectivePermissionProviderRegistry',

  // Widget manager
  widgetManager: 'WidgetManagerService',
  widgetRestorerRegistry: 'WidgetRestorerRegistry',
  elementTreeWidgetPermissionRegistry: 'ElementTreeWidgetPermissionRegistry',

  // Background processor
  backgroundProcessor: 'BackgroundProcessorService',

  // Form services
  debouncedFormRegistry: 'DebouncedFormRegistry',

  // Global message system
  globalMessageBusProcess: 'GlobalMessageBusProcess',
  globalMessageBus: 'GlobalMessageBus',

  // Dynamic Type Theme instances
  'DynamicTypes/Theme/StudioDefaultLight': 'DynamicTypes/Theme/StudioDefaultLight',
  'DynamicTypes/Theme/StudioDefaultDark': 'DynamicTypes/Theme/StudioDefaultDark',

  // Assets
  'Asset/Editor/TypeRegistry': 'Asset/Editor/TypeRegistry',
  'Asset/Editor/TypeComponentRegistry': 'Asset/Editor/TypeComponentRegistry',
  'Asset/Editor/DocumentTabManager': 'Asset/Editor/DocumentTabManager',
  'Asset/Editor/FolderTabManager': 'Asset/Editor/FolderTabManager',
  'Asset/Editor/ImageTabManager': 'Asset/Editor/ImageTabManager',
  'Asset/Editor/TextTabManager': 'Asset/Editor/TextTabManager',
  'Asset/Editor/VideoTabManager': 'Asset/Editor/VideoTabManager',
  'Asset/Editor/AudioTabManager': 'Asset/Editor/AudioTabManager',
  'Asset/Editor/ArchiveTabManager': 'Asset/Editor/ArchiveTabManager',
  'Asset/Editor/UnknownTabManager': 'Asset/Editor/UnknownTabManager',
  'Asset/ThumbnailService': 'Asset/ThumbnailService',
  'Asset/Listing/Builder': 'Asset/Listing/Builder',

  // Data Objects
  'DataObject/Editor/TypeRegistry': 'DataObject/Editor/TypeRegistry',
  'DataObject/Editor/ObjectTabManager': 'DataObject/Editor/ObjectTabManager',
  'DataObject/Editor/VariantTabManager': 'DataObject/Editor/VariantTabManager',
  'DataObject/Editor/FolderTabManager': 'DataObject/Editor/FolderTabManager',
  'DataObject/Listing/Builder': 'DataObject/Listing/Builder',

  // Documents
  'Document/Editor/TypeRegistry': 'Document/Editor/TypeRegistry',
  'Document/Editor/PageTabManager': 'Document/Editor/PageTabManager',
  'Document/Editor/EmailTabManager': 'Document/Editor/EmailTabManager',
  'Document/Editor/FolderTabManager': 'Document/Editor/FolderTabManager',
  'Document/Editor/HardlinkTabManager': 'Document/Editor/HardlinkTabManager',
  'Document/Editor/LinkTabManager': 'Document/Editor/LinkTabManager',
  'Document/Editor/SnippetTabManager': 'Document/Editor/SnippetTabManager',

  // Document Sidebar Managers
  'Document/Editor/Sidebar/PageSidebarManager': 'Document/Editor/Sidebar/PageSidebarManager',
  'Document/Editor/Sidebar/SnippetSidebarManager': 'Document/Editor/Sidebar/SnippetSidebarManager',
  'Document/Editor/Sidebar/EmailSidebarManager': 'Document/Editor/Sidebar/EmailSidebarManager',
  'Document/Editor/Sidebar/LinkSidebarManager': 'Document/Editor/Sidebar/LinkSidebarManager',
  'Document/Editor/Sidebar/HardlinkSidebarManager': 'Document/Editor/Sidebar/HardlinkSidebarManager',
  'Document/Editor/Sidebar/FolderSidebarManager': 'Document/Editor/Sidebar/FolderSidebarManager',

  // icon library
  iconLibrary: 'IconLibrary',
  iconColorGroupsRegistry: 'IconColorGroupsRegistry',

  // Grid
  'Grid/TypeRegistry': 'Grid/TypeRegistry',

  // dynamic types
  ...dynamicTypeRegistriesServiceIds,

  'DynamicTypes/FieldFilter/DataObjectAdapter': 'DynamicTypes/FieldFilter/DataObjectAdapter',
  'DynamicTypes/FieldFilter/DataObjectObjectBrick': 'DynamicTypes/FieldFilter/DataObjectObjectBrick',
  'DynamicTypes/FieldFilter/String': 'DynamicTypes/FieldFilter/String',
  'DynamicTypes/FieldFilter/None': 'DynamicTypes/FieldFilter/None',
  'DynamicTypes/FieldFilter/Id': 'DynamicTypes/FieldFilter/Id',
  'DynamicTypes/FieldFilter/Number': 'DynamicTypes/FieldFilter/Number',
  'DynamicTypes/FieldFilter/Multiselect': 'DynamicTypes/FieldFilter/Multiselect',
  'DynamicTypes/FieldFilter/Date': 'DynamicTypes/FieldFilter/Date',
  'DynamicTypes/FieldFilter/Boolean': 'DynamicTypes/FieldFilter/Boolean',
  'DynamicTypes/FieldFilter/BooleanSelect': 'DynamicTypes/FieldFilter/BooleanSelect',
  'DynamicTypes/FieldFilter/Consent': 'DynamicTypes/FieldFilter/Consent',
  'DynamicTypes/FieldFilter/ClassificationStore': 'DynamicTypes/FieldFilter/ClassificationStore',
  'DynamicTypes/FieldFilter/InputQuantityValue': 'DynamicTypes/FieldFilter/InputQuantityValue',
  'DynamicTypes/FieldFilter/QuantityValue': 'DynamicTypes/FieldFilter/QuantityValue',
  'DynamicTypes/FieldFilter/Datetime': 'DynamicTypes/FieldFilter/Datetime',
  'DynamicTypes/FieldFilter/Time': 'DynamicTypes/FieldFilter/Time',
  'DynamicTypes/FieldFilter/Color': 'DynamicTypes/FieldFilter/Color',
  'DynamicTypes/FieldFilter/Relation': 'DynamicTypes/FieldFilter/Relation',

  'DynamicTypes/BatchEdit/Text': 'DynamicTypes/BatchEdit/Text',
  'DynamicTypes/BatchEdit/TextArea': 'DynamicTypes/BatchEdit/TextArea',
  'DynamicTypes/BatchEdit/Datetime': 'DynamicTypes/BatchEdit/Datetime',
  'DynamicTypes/BatchEdit/Select': 'DynamicTypes/BatchEdit/Select',
  'DynamicTypes/BatchEdit/Checkbox': 'DynamicTypes/BatchEdit/Checkbox',
  'DynamicTypes/BatchEdit/ElementDropzone': 'DynamicTypes/BatchEdit/ElementDropzone',
  'DynamicTypes/BatchEdit/ClassificationStore': 'DynamicTypes/BatchEdit/ClassificationStore',
  'DynamicTypes/BatchEdit/DataObjectAdapter': 'DynamicTypes/BatchEdit/DataObjectAdapter',
  'DynamicTypes/BatchEdit/DataObjectObjectBrick': 'DynamicTypes/BatchEdit/DataObjectObjectBrick',

  'DynamicTypes/GridCell/Text': 'DynamicTypes/GridCell/Text',
  'DynamicTypes/GridCell/String': 'DynamicTypes/GridCell/String',
  'DynamicTypes/GridCell/Integer': 'DynamicTypes/GridCell/Integer',
  'DynamicTypes/GridCell/Error': 'DynamicTypes/GridCell/Error',
  'DynamicTypes/GridCell/Array': 'DynamicTypes/GridCell/Array',
  'DynamicTypes/GridCell/Textarea': 'DynamicTypes/GridCell/Textarea',
  'DynamicTypes/GridCell/Number': 'DynamicTypes/GridCell/Number',
  'DynamicTypes/GridCell/Select': 'DynamicTypes/GridCell/Select',
  'DynamicTypes/GridCell/MultiSelect': 'DynamicTypes/GridCell/MultiSelect',
  'DynamicTypes/GridCell/Checkbox': 'DynamicTypes/GridCell/Checkbox',
  'DynamicTypes/GridCell/Boolean': 'DynamicTypes/GridCell/Boolean',
  'DynamicTypes/GridCell/Date': 'DynamicTypes/GridCell/Date',
  'DynamicTypes/GridCell/Time': 'DynamicTypes/GridCell/Time',
  'DynamicTypes/GridCell/DateTime': 'DynamicTypes/GridCell/DateTime',
  'DynamicTypes/GridCell/AssetLink': 'DynamicTypes/GridCell/AssetLink',
  'DynamicTypes/GridCell/ObjectLink': 'DynamicTypes/GridCell/ObjectLink',
  'DynamicTypes/GridCell/DocumentLink': 'DynamicTypes/GridCell/DocumentLink',
  'DynamicTypes/GridCell/OpenElement': 'DynamicTypes/GridCell/OpenElement',
  'DynamicTypes/GridCell/AssetPreview': 'DynamicTypes/GridCell/AssetPreview',
  'DynamicTypes/GridCell/AssetActions': 'DynamicTypes/GridCell/AssetActions',
  'DynamicTypes/GridCell/DataObjectActions': 'DynamicTypes/GridCell/DataObjectActions',
  'DynamicTypes/GridCell/DependencyTypeIcon': 'DynamicTypes/GridCell/DependencyTypeIcon',
  'DynamicTypes/GridCell/ElementSubtypeIcon': 'DynamicTypes/GridCell/ElementSubtypeIcon',
  'DynamicTypes/GridCell/AssetCustomMetadataIcon': 'DynamicTypes/GridCell/AssetCustomMetadataIcon',
  'DynamicTypes/GridCell/AssetCustomMetadataValue': 'DynamicTypes/GridCell/AssetCustomMetadataValue',
  'DynamicTypes/GridCell/PropertyIcon': 'DynamicTypes/GridCell/PropertyIcon',
  'DynamicTypes/GridCell/PropertyValue': 'DynamicTypes/GridCell/PropertyValue',
  'DynamicTypes/GridCell/WebsiteSettingsValue': 'DynamicTypes/GridCell/WebsiteSettingsValue',
  'DynamicTypes/GridCell/ScheduleActionsSelect': 'DynamicTypes/GridCell/ScheduleActionsSelect',
  'DynamicTypes/GridCell/VersionsIdSelect': 'DynamicTypes/GridCell/VersionsIdSelect',
  'DynamicTypes/GridCell/AssetVersionPreviewFieldLabel': 'DynamicTypes/GridCell/AssetVersionPreviewFieldLabel',
  'DynamicTypes/GridCell/Asset': 'DynamicTypes/GridCell/Asset',
  'DynamicTypes/GridCell/Object': 'DynamicTypes/GridCell/Object',
  'DynamicTypes/GridCell/Document': 'DynamicTypes/GridCell/Document',
  'DynamicTypes/GridCell/Element': 'DynamicTypes/GridCell/Element',
  'DynamicTypes/GridCell/LanguageSelect': 'DynamicTypes/GridCell/LanguageSelect',
  'DynamicTypes/GridCell/Translate': 'DynamicTypes/GridCell/Translate',
  'DynamicTypes/GridCell/DataObjectAdapter': 'DynamicTypes/GridCell/DataObjectAdapter',
  'DynamicTypes/GridCell/ClassificationStore': 'DynamicTypes/GridCell/ClassificationStore',
  'DynamicTypes/GridCell/DataObjectAdvanced': 'DynamicTypes/GridCell/DataObjectAdvanced',
  'DynamicTypes/GridCell/DataObjectObjectBrick': 'DynamicTypes/GridCell/DataObjectObjectBrick',

  'DynamicTypes/Listing/Text': 'DynamicTypes/Listing/Text',
  'DynamicTypes/Listing/AssetLink': 'DynamicTypes/Listing/AssetLink',
  'DynamicTypes/Listing/Select': 'DynamicTypes/Listing/Select',

  'DynamicTypes/Metadata/Asset': 'DynamicTypes/Metadata/Asset',
  'DynamicTypes/Metadata/Document': 'DynamicTypes/Metadata/Document',
  'DynamicTypes/Metadata/Object': 'DynamicTypes/Metadata/Object',
  'DynamicTypes/Metadata/Input': 'DynamicTypes/Metadata/Input',
  'DynamicTypes/Metadata/Textarea': 'DynamicTypes/Metadata/Textarea',
  'DynamicTypes/Metadata/Checkbox': 'DynamicTypes/Metadata/Checkbox',
  'DynamicTypes/Metadata/Select': 'DynamicTypes/Metadata/Select',
  'DynamicTypes/Metadata/Date': 'DynamicTypes/Metadata/Date',

  'DynamicTypes/CustomReportDefinition/Sql': 'DynamicTypes/CustomReportDefinition/Sql',

  // Object layout
  'DynamicTypes/ObjectLayout/Panel': 'DynamicTypes/ObjectLayout/Panel',
  'DynamicTypes/ObjectLayout/Tabpanel': 'DynamicTypes/ObjectLayout/Tabpanel',
  'DynamicTypes/ObjectLayout/Accordion': 'DynamicTypes/ObjectLayout/Accordion',
  'DynamicTypes/ObjectLayout/Region': 'DynamicTypes/ObjectLayout/Region',
  'DynamicTypes/ObjectLayout/Text': 'DynamicTypes/ObjectLayout/Text',
  'DynamicTypes/ObjectLayout/Fieldset': 'DynamicTypes/ObjectLayout/Fieldset',
  'DynamicTypes/ObjectLayout/FieldContainer': 'DynamicTypes/ObjectLayout/FieldContainer',
  'DynamicTypes/ObjectLayout/Iframe': 'DynamicTypes/ObjectLayout/Iframe',

  // Object data
  'DynamicTypes/ObjectData/Input': 'DynamicTypes/ObjectData/Input',
  'DynamicTypes/ObjectData/Textarea': 'DynamicTypes/ObjectData/Textarea',
  'DynamicTypes/ObjectData/Wysiwyg': 'DynamicTypes/ObjectData/Wysiwyg',
  'DynamicTypes/ObjectData/Password': 'DynamicTypes/ObjectData/Password',
  'DynamicTypes/ObjectData/InputQuantityValue': 'DynamicTypes/ObjectData/InputQuantityValue',
  'DynamicTypes/ObjectData/Select': 'DynamicTypes/ObjectData/Select',
  'DynamicTypes/ObjectData/MultiSelect': 'DynamicTypes/ObjectData/MultiSelect',
  'DynamicTypes/ObjectData/Language': 'DynamicTypes/ObjectData/Language',
  'DynamicTypes/ObjectData/LanguageMultiSelect': 'DynamicTypes/ObjectData/LanguageMultiSelect',
  'DynamicTypes/ObjectData/Country': 'DynamicTypes/ObjectData/Country',
  'DynamicTypes/ObjectData/CountryMultiSelect': 'DynamicTypes/ObjectData/CountryMultiSelect',
  'DynamicTypes/ObjectData/User': 'DynamicTypes/ObjectData/User',
  'DynamicTypes/ObjectData/BooleanSelect': 'DynamicTypes/ObjectData/BooleanSelect',
  'DynamicTypes/ObjectData/Numeric': 'DynamicTypes/ObjectData/Numeric',
  'DynamicTypes/ObjectData/NumericRange': 'DynamicTypes/ObjectData/NumericRange',
  'DynamicTypes/ObjectData/Slider': 'DynamicTypes/ObjectData/Slider',
  'DynamicTypes/ObjectData/QuantityValue': 'DynamicTypes/ObjectData/QuantityValue',
  'DynamicTypes/ObjectData/QuantityValueRange': 'DynamicTypes/ObjectData/QuantityValueRange',
  'DynamicTypes/ObjectData/Consent': 'DynamicTypes/ObjectData/Consent',
  'DynamicTypes/ObjectData/Firstname': 'DynamicTypes/ObjectData/Firstname',
  'DynamicTypes/ObjectData/Lastname': 'DynamicTypes/ObjectData/Lastname',
  'DynamicTypes/ObjectData/Email': 'DynamicTypes/ObjectData/Email',
  'DynamicTypes/ObjectData/Gender': 'DynamicTypes/ObjectData/Gender',
  'DynamicTypes/ObjectData/RgbaColor': 'DynamicTypes/ObjectData/RgbaColor',
  'DynamicTypes/ObjectData/EncryptedField': 'DynamicTypes/ObjectData/EncryptedField',
  'DynamicTypes/ObjectData/CalculatedValue': 'DynamicTypes/ObjectData/CalculatedValue',
  'DynamicTypes/ObjectData/Checkbox': 'DynamicTypes/ObjectData/Checkbox',
  'DynamicTypes/ObjectData/Link': 'DynamicTypes/ObjectData/Link',
  'DynamicTypes/ObjectData/UrlSlug': 'DynamicTypes/ObjectData/UrlSlug',
  'DynamicTypes/ObjectData/Date': 'DynamicTypes/ObjectData/Date',
  'DynamicTypes/ObjectData/Datetime': 'DynamicTypes/ObjectData/Datetime',
  'DynamicTypes/ObjectData/DateRange': 'DynamicTypes/ObjectData/DateRange',
  'DynamicTypes/ObjectData/Time': 'DynamicTypes/ObjectData/Time',
  'DynamicTypes/ObjectData/ExternalImage': 'DynamicTypes/ObjectData/ExternalImage',
  'DynamicTypes/ObjectData/Image': 'DynamicTypes/ObjectData/Image',
  'DynamicTypes/ObjectData/Video': 'DynamicTypes/ObjectData/Video',
  'DynamicTypes/ObjectData/HotspotImage': 'DynamicTypes/ObjectData/HotspotImage',
  'DynamicTypes/ObjectData/ImageGallery': 'DynamicTypes/ObjectData/ImageGallery',
  'DynamicTypes/ObjectData/GeoPoint': 'DynamicTypes/ObjectData/GeoPoint',
  'DynamicTypes/ObjectData/GeoBounds': 'DynamicTypes/ObjectData/GeoBounds',
  'DynamicTypes/ObjectData/GeoPolygon': 'DynamicTypes/ObjectData/GeoPolygon',
  'DynamicTypes/ObjectData/GeoPolyLine': 'DynamicTypes/ObjectData/GeoPolyLine',
  'DynamicTypes/ObjectData/ManyToOneRelation': 'DynamicTypes/ObjectData/ManyToOneRelation',
  'DynamicTypes/ObjectData/ManyToManyRelation': 'DynamicTypes/ObjectData/ManyToManyRelation',
  'DynamicTypes/ObjectData/ManyToManyObjectRelation': 'DynamicTypes/ObjectData/ManyToManyObjectRelation',
  'DynamicTypes/ObjectData/AdvancedManyToManyRelation': 'DynamicTypes/ObjectData/AdvancedManyToManyRelation',
  'DynamicTypes/ObjectData/AdvancedManyToManyObjectRelation': 'DynamicTypes/ObjectData/AdvancedManyToManyObjectRelation',
  'DynamicTypes/ObjectData/ReverseObjectRelation': 'DynamicTypes/ObjectData/ReverseObjectRelation',
  'DynamicTypes/ObjectData/Table': 'DynamicTypes/ObjectData/Table',
  'DynamicTypes/ObjectData/StructuredTable': 'DynamicTypes/ObjectData/StructuredTable',
  'DynamicTypes/ObjectData/Block': 'DynamicTypes/ObjectData/Block',
  'DynamicTypes/ObjectData/LocalizedFields': 'DynamicTypes/ObjectData/LocalizedFields',
  'DynamicTypes/ObjectData/FieldCollection': 'DynamicTypes/ObjectData/FieldCollection',
  'DynamicTypes/ObjectData/ObjectBrick': 'DynamicTypes/ObjectData/ObjectBrick',
  'DynamicTypes/ObjectData/ClassificationStore': 'DynamicTypes/ObjectData/ClassificationStore',

  // Document editables
  'DynamicTypes/DocumentEditable/Area': 'DynamicTypes/DocumentEditable/Area',
  'DynamicTypes/DocumentEditable/Areablock': 'DynamicTypes/DocumentEditable/Areablock',
  'DynamicTypes/DocumentEditable/Block': 'DynamicTypes/DocumentEditable/Block',
  'DynamicTypes/DocumentEditable/Checkbox': 'DynamicTypes/DocumentEditable/Checkbox',
  'DynamicTypes/DocumentEditable/Date': 'DynamicTypes/DocumentEditable/Date',
  'DynamicTypes/DocumentEditable/Embed': 'DynamicTypes/DocumentEditable/Embed',
  'DynamicTypes/DocumentEditable/Image': 'DynamicTypes/DocumentEditable/Image',
  'DynamicTypes/DocumentEditable/Input': 'DynamicTypes/DocumentEditable/Input',
  'DynamicTypes/DocumentEditable/Link': 'DynamicTypes/DocumentEditable/Link',
  'DynamicTypes/DocumentEditable/MultiSelect': 'DynamicTypes/DocumentEditable/MultiSelect',
  'DynamicTypes/DocumentEditable/Numeric': 'DynamicTypes/DocumentEditable/Numeric',
  'DynamicTypes/DocumentEditable/Pdf': 'DynamicTypes/DocumentEditable/Pdf',
  'DynamicTypes/DocumentEditable/Relation': 'DynamicTypes/DocumentEditable/Relation',
  'DynamicTypes/DocumentEditable/Relations': 'DynamicTypes/DocumentEditable/Relations',
  'DynamicTypes/DocumentEditable/Renderlet': 'DynamicTypes/DocumentEditable/Renderlet',
  'DynamicTypes/DocumentEditable/ScheduledBlock': 'DynamicTypes/DocumentEditable/ScheduledBlock',
  'DynamicTypes/DocumentEditable/Select': 'DynamicTypes/DocumentEditable/Select',
  'DynamicTypes/DocumentEditable/Snippet': 'DynamicTypes/DocumentEditable/Snippet',
  'DynamicTypes/DocumentEditable/Table': 'DynamicTypes/DocumentEditable/Table',
  'DynamicTypes/DocumentEditable/Textarea': 'DynamicTypes/DocumentEditable/Textarea',
  'DynamicTypes/DocumentEditable/Video': 'DynamicTypes/DocumentEditable/Video',
  'DynamicTypes/DocumentEditable/Wysiwyg': 'DynamicTypes/DocumentEditable/Wysiwyg',

  // Document editable dialog layout
  'DynamicTypes/EditableDialogLayout/Tabpanel': 'DynamicTypes/EditableDialogLayout/Tabpanel',
  'DynamicTypes/EditableDialogLayout/Panel': 'DynamicTypes/EditableDialogLayout/Panel',

  // Document types
  'DynamicTypes/Document/Page': 'DynamicTypes/Document/Page',
  'DynamicTypes/Document/Newsletter': 'DynamicTypes/Document/Newsletter',
  'DynamicTypes/Document/Snippet': 'DynamicTypes/Document/Snippet',
  'DynamicTypes/Document/Link': 'DynamicTypes/Document/Link',
  'DynamicTypes/Document/Hardlink': 'DynamicTypes/Document/Hardlink',
  'DynamicTypes/Document/Email': 'DynamicTypes/Document/Email',
  'DynamicTypes/Document/Folder': 'DynamicTypes/Document/Folder',

  // Asset types
  'DynamicTypes/Asset/Video': 'DynamicTypes/Asset/Video',
  'DynamicTypes/Asset/Audio': 'DynamicTypes/Asset/Audio',
  'DynamicTypes/Asset/Image': 'DynamicTypes/Asset/Image',
  'DynamicTypes/Asset/Document': 'DynamicTypes/Asset/Document',
  'DynamicTypes/Asset/Archive': 'DynamicTypes/Asset/Archive',
  'DynamicTypes/Asset/Unknown': 'DynamicTypes/Asset/Unknown',
  'DynamicTypes/Asset/Folder': 'DynamicTypes/Asset/Folder',
  'DynamicTypes/Asset/Text': 'DynamicTypes/Asset/Text',

  // Object types
  'DynamicTypes/Object/Folder': 'DynamicTypes/Object/Folder',
  'DynamicTypes/Object/Object': 'DynamicTypes/Object/Object',
  'DynamicTypes/Object/Variant': 'DynamicTypes/Object/Variant',

  // Advanced Columns source fields
  'DynamicTypes/Grid/SourceFields/Text': 'DynamicTypes/Grid/SourceFields/Text',
  'DynamicTypes/Grid/SourceFields/SimpleField': 'DynamicTypes/Grid/SourceFields/SimpleField',
  'DynamicTypes/Grid/SourceFields/RelationField': 'DynamicTypes/Grid/SourceFields/RelationField',

  // Advanced Columns transformers
  'DynamicTypes/Grid/Transformers/BooleanFormatter': 'DynamicTypes/Grid/Transformers/BooleanFormatter',
  'DynamicTypes/Grid/Transformers/DateFormatter': 'DynamicTypes/Grid/Transformers/DateFormatter',
  'DynamicTypes/Grid/Transformers/ElementCounter': 'DynamicTypes/Grid/Transformers/ElementCounter',
  'DynamicTypes/Grid/Transformers/TwigOperator': 'DynamicTypes/Grid/Transformers/TwigOperator',
  'DynamicTypes/Grid/Transformers/Anonymizer': 'DynamicTypes/Grid/Transformers/Anonymizer',
  'DynamicTypes/Grid/Transformers/Blur': 'DynamicTypes/Grid/Transformers/Blur',
  'DynamicTypes/Grid/Transformers/ChangeCase': 'DynamicTypes/Grid/Transformers/ChangeCase',
  'DynamicTypes/Grid/Transformers/Combine': 'DynamicTypes/Grid/Transformers/Combine',
  'DynamicTypes/Grid/Transformers/Explode': 'DynamicTypes/Grid/Transformers/Explode',
  'DynamicTypes/Grid/Transformers/StringReplace': 'DynamicTypes/Grid/Transformers/StringReplace',
  'DynamicTypes/Grid/Transformers/Substring': 'DynamicTypes/Grid/Transformers/Substring',
  'DynamicTypes/Grid/Transformers/Trim': 'DynamicTypes/Grid/Transformers/Trim',
  'DynamicTypes/Grid/Transformers/Translate': 'DynamicTypes/Grid/Transformers/Translate',
  'DynamicTypes/Grid/Transformers/PHPCode': 'DynamicTypes/Grid/Transformers/PHPCode',

  // Widget Editor types
  'DynamicTypes/WidgetEditor/ElementTree': 'DynamicTypes/WidgetEditor/ElementTree',

  // Execution engine
  'ExecutionEngine/JobComponentRegistry': 'ExecutionEngine/JobComponentRegistry',

  // Execution Engine
  executionEngine: 'ExecutionEngine',

  // Component registry
  'App/ComponentRegistry/ComponentRegistry': 'App/ComponentRegistry/ComponentRegistry',

  // Context menu registry
  'App/ContextMenuRegistry/ContextMenuRegistry': 'App/ContextMenuRegistry/ContextMenuRegistry',

  // Document required fields validation service
  'Document/RequiredFieldsValidationService': 'Document/RequiredFieldsValidationService',

  // Processor registries
  'Document/ProcessorRegistry/UrlProcessor': 'Document/ProcessorRegistry/UrlProcessor',
  'Document/ProcessorRegistry/SaveDataProcessor': 'Document/ProcessorRegistry/SaveDataProcessor',
  'DataObject/ProcessorRegistry/SaveDataProcessor': 'DataObject/ProcessorRegistry/SaveDataProcessor',
  'Asset/ProcessorRegistry/SaveDataProcessor': 'Asset/ProcessorRegistry/SaveDataProcessor',
  'Element/ProcessorRegistry/IconProcessor': 'Element/ProcessorRegistry/IconProcessor',
  'WidgetManager/ProcessorRegistry/PerspectiveProcessor': 'WidgetManager/ProcessorRegistry/PerspectiveProcessor',

  // AppLoader Registry
  'AppLoader/Registry': 'AppLoader/Registry',

  // Field Definitions
  'DynamicTypes/FieldDefinition/Block': 'DynamicTypes/FieldDefinition/Block',
  'DynamicTypes/FieldDefinition/Input': 'DynamicTypes/FieldDefinition/Input',
  'DynamicTypes/FieldDefinition/Accordion': 'DynamicTypes/FieldDefinition/Accordion',
  'DynamicTypes/FieldDefinition/FieldContainer': 'DynamicTypes/FieldDefinition/FieldContainer',
  'DynamicTypes/FieldDefinition/Fieldset': 'DynamicTypes/FieldDefinition/Fieldset',
  'DynamicTypes/FieldDefinition/Iframe': 'DynamicTypes/FieldDefinition/Iframe',
  'DynamicTypes/FieldDefinition/Panel': 'DynamicTypes/FieldDefinition/Panel',
  'DynamicTypes/FieldDefinition/Region': 'DynamicTypes/FieldDefinition/Region',
  'DynamicTypes/FieldDefinition/Tabpanel': 'DynamicTypes/FieldDefinition/Tabpanel',
  'DynamicTypes/FieldDefinition/Text': 'DynamicTypes/FieldDefinition/Text',
  'DynamicTypes/FieldDefinition/Textarea': 'DynamicTypes/FieldDefinition/Textarea',
  'DynamicTypes/FieldDefinition/Wysiwyg': 'DynamicTypes/FieldDefinition/Wysiwyg',
  'DynamicTypes/FieldDefinition/Password': 'DynamicTypes/FieldDefinition/Password',
  'DynamicTypes/FieldDefinition/InputQuantityValue': 'DynamicTypes/FieldDefinition/InputQuantityValue',
  'DynamicTypes/FieldDefinition/Number': 'DynamicTypes/FieldDefinition/Number',
  'DynamicTypes/FieldDefinition/NumericRange': 'DynamicTypes/FieldDefinition/NumericRange',
  'DynamicTypes/FieldDefinition/Slider': 'DynamicTypes/FieldDefinition/Slider',
  'DynamicTypes/FieldDefinition/QuantityValue': 'DynamicTypes/FieldDefinition/QuantityValue',
  'DynamicTypes/FieldDefinition/QuantityValueRange': 'DynamicTypes/FieldDefinition/QuantityValueRange',
  'DynamicTypes/FieldDefinition/Date': 'DynamicTypes/FieldDefinition/Date',
  'DynamicTypes/FieldDefinition/DateTime': 'DynamicTypes/FieldDefinition/DateTime',
  'DynamicTypes/FieldDefinition/DateRange': 'DynamicTypes/FieldDefinition/DateRange',
  'DynamicTypes/FieldDefinition/Time': 'DynamicTypes/FieldDefinition/Time',
  'DynamicTypes/FieldDefinition/Image': 'DynamicTypes/FieldDefinition/Image',
  'DynamicTypes/FieldDefinition/ExternalImage': 'DynamicTypes/FieldDefinition/ExternalImage',
  'DynamicTypes/FieldDefinition/ImageGallery': 'DynamicTypes/FieldDefinition/ImageGallery',
  'DynamicTypes/FieldDefinition/Video': 'DynamicTypes/FieldDefinition/Video',
  'DynamicTypes/FieldDefinition/HotspotImage': 'DynamicTypes/FieldDefinition/HotspotImage',
  'DynamicTypes/FieldDefinition/Geopoint': 'DynamicTypes/FieldDefinition/Geopoint',
  'DynamicTypes/FieldDefinition/Geobounds': 'DynamicTypes/FieldDefinition/Geobounds',
  'DynamicTypes/FieldDefinition/Geopolygon': 'DynamicTypes/FieldDefinition/Geopolygon',
  'DynamicTypes/FieldDefinition/Geopolyline': 'DynamicTypes/FieldDefinition/Geopolyline',
  'DynamicTypes/FieldDefinition/Select': 'DynamicTypes/FieldDefinition/Select',
  'DynamicTypes/FieldDefinition/BooleanSelect': 'DynamicTypes/FieldDefinition/BooleanSelect',
  'DynamicTypes/FieldDefinition/Multiselect': 'DynamicTypes/FieldDefinition/Multiselect',
  'DynamicTypes/FieldDefinition/User': 'DynamicTypes/FieldDefinition/User',
  'DynamicTypes/FieldDefinition/Country': 'DynamicTypes/FieldDefinition/Country',
  'DynamicTypes/FieldDefinition/Language': 'DynamicTypes/FieldDefinition/Language',
  'DynamicTypes/FieldDefinition/CountryMultiselect': 'DynamicTypes/FieldDefinition/CountryMultiselect',
  'DynamicTypes/FieldDefinition/LanguageMultiselect': 'DynamicTypes/FieldDefinition/LanguageMultiselect',
  'DynamicTypes/FieldDefinition/RgbaColor': 'DynamicTypes/FieldDefinition/RgbaColor',
  'DynamicTypes/FieldDefinition/EncryptedField': 'DynamicTypes/FieldDefinition/EncryptedField',
  'DynamicTypes/FieldDefinition/UrlSlug': 'DynamicTypes/FieldDefinition/UrlSlug',
  'DynamicTypes/FieldDefinition/Checkbox': 'DynamicTypes/FieldDefinition/Checkbox',
  'DynamicTypes/FieldDefinition/Link': 'DynamicTypes/FieldDefinition/Link',
  'DynamicTypes/FieldDefinition/CalculatedValue': 'DynamicTypes/FieldDefinition/CalculatedValue',
  'DynamicTypes/FieldDefinition/ManyToOne': 'DynamicTypes/FieldDefinition/ManyToOne',
  'DynamicTypes/FieldDefinition/ManyToMany': 'DynamicTypes/FieldDefinition/ManyToMany',
  'DynamicTypes/FieldDefinition/ManyToManyObject': 'DynamicTypes/FieldDefinition/ManyToManyObject',
  'DynamicTypes/FieldDefinition/AdvancedManyToMany': 'DynamicTypes/FieldDefinition/AdvancedManyToMany',
  'DynamicTypes/FieldDefinition/AdvancedManyToManyObject': 'DynamicTypes/FieldDefinition/AdvancedManyToManyObject',
  'DynamicTypes/FieldDefinition/ReverseObject': 'DynamicTypes/FieldDefinition/ReverseObject',
  'DynamicTypes/FieldDefinition/Table': 'DynamicTypes/FieldDefinition/Table',
  'DynamicTypes/FieldDefinition/StructuredTable': 'DynamicTypes/FieldDefinition/StructuredTable',
  'DynamicTypes/FieldDefinition/Fieldcollections': 'DynamicTypes/FieldDefinition/Fieldcollections',
  'DynamicTypes/FieldDefinition/Objectbricks': 'DynamicTypes/FieldDefinition/Objectbricks',
  'DynamicTypes/FieldDefinition/Classificationstore': 'DynamicTypes/FieldDefinition/Classificationstore',
  'DynamicTypes/FieldDefinition/Localizedfields': 'DynamicTypes/FieldDefinition/Localizedfields',
  'DynamicTypes/FieldDefinition/Firstname': 'DynamicTypes/FieldDefinition/Firstname',
  'DynamicTypes/FieldDefinition/Lastname': 'DynamicTypes/FieldDefinition/Lastname',
  'DynamicTypes/FieldDefinition/Email': 'DynamicTypes/FieldDefinition/Email',
  'DynamicTypes/FieldDefinition/Gender': 'DynamicTypes/FieldDefinition/Gender',
  'DynamicTypes/FieldDefinition/Consent': 'DynamicTypes/FieldDefinition/Consent',

  // GDPR Providers
  'DynamicTypes/GDPRProvider/DataObjects': 'DynamicTypes/GDPRProvider/DataObjects',
  'DynamicTypes/GDPRProvider/Assets': 'DynamicTypes/GDPRProvider/Assets',
  'DynamicTypes/GDPRProvider/Users': 'DynamicTypes/GDPRProvider/Users',
  'DynamicTypes/GDPRProvider/Emails': 'DynamicTypes/GDPRProvider/Emails'
}
