/**
 * This source file is available under the terms of the
 * Pimcore Open Core License (POCL)
 * Full copyright and license information is available in
 * LICENSE.md which is distributed with this source code.
 *
 *  @copyright  Copyright (c) Pimcore GmbH (https://www.pimcore.com)
 *  @license    Pimcore Open Core License (POCL)
 */

import { moduleSystem } from '@Pimcore/app/module-system/module-system'
import { type DynamicTypeFieldDefinitionRegistry } from '@Pimcore/modules/field-definitions/dynamic-types/dynamic-type-field-definition-registry'
import { container } from '@sdk/app'

moduleSystem.registerModule({
  onInit: () => {
    const fieldDefinitionRegistry = container.get<DynamicTypeFieldDefinitionRegistry>('DynamicTypes/FieldDefinitionRegistry')

    fieldDefinitionRegistry.registerDynamicType(container.get('DynamicTypes/FieldDefinition/Block'))
    fieldDefinitionRegistry.registerDynamicType(container.get('DynamicTypes/FieldDefinition/Input'))
    fieldDefinitionRegistry.registerDynamicType(container.get('DynamicTypes/FieldDefinition/Textarea'))
    fieldDefinitionRegistry.registerDynamicType(container.get('DynamicTypes/FieldDefinition/Wysiwyg'))
    fieldDefinitionRegistry.registerDynamicType(container.get('DynamicTypes/FieldDefinition/Password'))
    fieldDefinitionRegistry.registerDynamicType(container.get('DynamicTypes/FieldDefinition/InputQuantityValue'))
    fieldDefinitionRegistry.registerDynamicType(container.get('DynamicTypes/FieldDefinition/Number'))
    fieldDefinitionRegistry.registerDynamicType(container.get('DynamicTypes/FieldDefinition/NumericRange'))
    fieldDefinitionRegistry.registerDynamicType(container.get('DynamicTypes/FieldDefinition/Slider'))
    fieldDefinitionRegistry.registerDynamicType(container.get('DynamicTypes/FieldDefinition/QuantityValue'))
    fieldDefinitionRegistry.registerDynamicType(container.get('DynamicTypes/FieldDefinition/QuantityValueRange'))
    fieldDefinitionRegistry.registerDynamicType(container.get('DynamicTypes/FieldDefinition/Date'))
    fieldDefinitionRegistry.registerDynamicType(container.get('DynamicTypes/FieldDefinition/DateTime'))
    fieldDefinitionRegistry.registerDynamicType(container.get('DynamicTypes/FieldDefinition/DateRange'))
    fieldDefinitionRegistry.registerDynamicType(container.get('DynamicTypes/FieldDefinition/Time'))
    fieldDefinitionRegistry.registerDynamicType(container.get('DynamicTypes/FieldDefinition/Image'))
    fieldDefinitionRegistry.registerDynamicType(container.get('DynamicTypes/FieldDefinition/ExternalImage'))
    fieldDefinitionRegistry.registerDynamicType(container.get('DynamicTypes/FieldDefinition/ImageGallery'))
    fieldDefinitionRegistry.registerDynamicType(container.get('DynamicTypes/FieldDefinition/Video'))
    fieldDefinitionRegistry.registerDynamicType(container.get('DynamicTypes/FieldDefinition/HotspotImage'))
    fieldDefinitionRegistry.registerDynamicType(container.get('DynamicTypes/FieldDefinition/Geopoint'))
    fieldDefinitionRegistry.registerDynamicType(container.get('DynamicTypes/FieldDefinition/Geobounds'))
    fieldDefinitionRegistry.registerDynamicType(container.get('DynamicTypes/FieldDefinition/Geopolygon'))
    fieldDefinitionRegistry.registerDynamicType(container.get('DynamicTypes/FieldDefinition/Geopolyline'))
    fieldDefinitionRegistry.registerDynamicType(container.get('DynamicTypes/FieldDefinition/Select'))
    fieldDefinitionRegistry.registerDynamicType(container.get('DynamicTypes/FieldDefinition/BooleanSelect'))
    fieldDefinitionRegistry.registerDynamicType(container.get('DynamicTypes/FieldDefinition/Multiselect'))
    fieldDefinitionRegistry.registerDynamicType(container.get('DynamicTypes/FieldDefinition/User'))
    fieldDefinitionRegistry.registerDynamicType(container.get('DynamicTypes/FieldDefinition/Country'))
    fieldDefinitionRegistry.registerDynamicType(container.get('DynamicTypes/FieldDefinition/Language'))
    fieldDefinitionRegistry.registerDynamicType(container.get('DynamicTypes/FieldDefinition/CountryMultiselect'))
    fieldDefinitionRegistry.registerDynamicType(container.get('DynamicTypes/FieldDefinition/LanguageMultiselect'))
    fieldDefinitionRegistry.registerDynamicType(container.get('DynamicTypes/FieldDefinition/RgbaColor'))
    fieldDefinitionRegistry.registerDynamicType(container.get('DynamicTypes/FieldDefinition/EncryptedField'))
    fieldDefinitionRegistry.registerDynamicType(container.get('DynamicTypes/FieldDefinition/UrlSlug'))
    fieldDefinitionRegistry.registerDynamicType(container.get('DynamicTypes/FieldDefinition/Checkbox'))
    fieldDefinitionRegistry.registerDynamicType(container.get('DynamicTypes/FieldDefinition/Link'))
    fieldDefinitionRegistry.registerDynamicType(container.get('DynamicTypes/FieldDefinition/CalculatedValue'))
    fieldDefinitionRegistry.registerDynamicType(container.get('DynamicTypes/FieldDefinition/ManyToOne'))
    fieldDefinitionRegistry.registerDynamicType(container.get('DynamicTypes/FieldDefinition/ManyToMany'))
    fieldDefinitionRegistry.registerDynamicType(container.get('DynamicTypes/FieldDefinition/ManyToManyObject'))
    fieldDefinitionRegistry.registerDynamicType(container.get('DynamicTypes/FieldDefinition/AdvancedManyToMany'))
    fieldDefinitionRegistry.registerDynamicType(container.get('DynamicTypes/FieldDefinition/AdvancedManyToManyObject'))
    fieldDefinitionRegistry.registerDynamicType(container.get('DynamicTypes/FieldDefinition/ReverseObject'))
    fieldDefinitionRegistry.registerDynamicType(container.get('DynamicTypes/FieldDefinition/Panel'))
    fieldDefinitionRegistry.registerDynamicType(container.get('DynamicTypes/FieldDefinition/Accordion'))
    fieldDefinitionRegistry.registerDynamicType(container.get('DynamicTypes/FieldDefinition/FieldContainer'))
    fieldDefinitionRegistry.registerDynamicType(container.get('DynamicTypes/FieldDefinition/Fieldset'))
    fieldDefinitionRegistry.registerDynamicType(container.get('DynamicTypes/FieldDefinition/Iframe'))
    fieldDefinitionRegistry.registerDynamicType(container.get('DynamicTypes/FieldDefinition/Region'))
    fieldDefinitionRegistry.registerDynamicType(container.get('DynamicTypes/FieldDefinition/Tabpanel'))
    fieldDefinitionRegistry.registerDynamicType(container.get('DynamicTypes/FieldDefinition/Text'))
    fieldDefinitionRegistry.registerDynamicType(container.get('DynamicTypes/FieldDefinition/Table'))
    fieldDefinitionRegistry.registerDynamicType(container.get('DynamicTypes/FieldDefinition/StructuredTable'))
    fieldDefinitionRegistry.registerDynamicType(container.get('DynamicTypes/FieldDefinition/Fieldcollections'))
    fieldDefinitionRegistry.registerDynamicType(container.get('DynamicTypes/FieldDefinition/Objectbricks'))
    fieldDefinitionRegistry.registerDynamicType(container.get('DynamicTypes/FieldDefinition/Classificationstore'))
    fieldDefinitionRegistry.registerDynamicType(container.get('DynamicTypes/FieldDefinition/Localizedfields'))
    fieldDefinitionRegistry.registerDynamicType(container.get('DynamicTypes/FieldDefinition/Consent'))
    fieldDefinitionRegistry.registerDynamicType(container.get('DynamicTypes/FieldDefinition/Firstname'))
    fieldDefinitionRegistry.registerDynamicType(container.get('DynamicTypes/FieldDefinition/Lastname'))
    fieldDefinitionRegistry.registerDynamicType(container.get('DynamicTypes/FieldDefinition/Email'))
    fieldDefinitionRegistry.registerDynamicType(container.get('DynamicTypes/FieldDefinition/Gender'))
  }
})
