pimcore_studio_ui:
    resource: "@PimcoreStudioUiBundle/src/Controller/DefaultController.php"
    type:     attribute
    prefix:   '%pimcore_studio_ui.url_path%'

pimcore_studio_ui_backend:
    resource: "@PimcoreStudioUiBundle/src/Controller/Backend/"
    type:     attribute
    prefix:   '%pimcore_studio_backend.url_prefix%'

pimcore_studio_ui_document_diffversions_html:
    path: /__pimcore-studio/documents/diff-versions-html
    defaults: { _controller: Pimcore\Bundle\StudioUiBundle\Controller\Backend\DocumentVersionsController::diffVersionsHtmlAction }